### ISSUE TITLE
insert # at end of buffer cause `cond: Args out of range` error

### ISSUE THREAD

**Issue by yuutayamada** [nim-lang/nim-mode#112]

**Comment by yuutayamada** [comment]
I pushed this because obviously it was my mistake...

**Comment by m-cat** [comment]
I'm seeing this same problem, easy enough to ignore but kind of annoying.

> insert # at end of buffer cause `cond: Args out of range` error

**Comment by yuutayamada** [comment]
Can you give me the minimized code? so I can add it to testing when the problem was solved.

**Comment by m-cat** [comment]
What do you mean by minimized code? I get this in every nim buffer, an example:

```
import tables, strutils

var wordFrequencies = initCountTable[string]()

for line in stdin.lines:
  for word in line.split(", "):
    wordFrequencies.inc(word)

echo "The most frequent word is '", wordFrequencies.largest, "'"
# ERROR when typing anything on this line
```

**Comment by yuutayamada** [comment]
Ah thank you for finding out what I meant (I wanted just short reproducable code)
But I couldn't reproduce the error from your example.

Maybe it would be help if you provide Emacs version, your OS, and error messages on `*messages*` buffer (if exist).

**Comment by kaushalmodi** [comment]
I saw this error too. It happens when typing a comment and when the point is also at the end of the buffer. 

I delete white space at end of lines and empty lines at end of buffer when saving. So I get this error when saving while the point is in a comment.

Workaround is to not allow the point to be at EOB while in comment.

**Comment by yuutayamada** [comment]
I'm not sure I can help this problem since I couldn't reproduce this issue.
I'd let this problem to someone who has same problem and has Emacs' debugging ability because nim-mode depends some Emacs' packages (flycheck, eldoc, company) as well as nimsuggest (Nim's editor support tool) in addition the error message is kind of vague... Anyway if I had the problem, I would turn off nimsuggest-mode/flycheck-mode/eldoc-mode/company-mode to narrow the problem. Hope this help.

For the record, I just put "#" at end of the buffer of koch.nim in nim repository and I didn't get the `cond: Args out of range` error. (also tried @m-cat's)

**Comment by kaushalmodi** [comment]
Here's the backtrace:

```
Debugger entered--Lisp error: (args-out-of-range 1069 1070)
  put-text-property(1069 1070 syntax-table (12))
  nim-syntax-commentify()
  #[514 "b\210`W\205n..
  syntax-propertize(1069)
  syntax-ppss()
  nim-indent-post-self-insert-function()
  self-insert-command(1)
  funcall-interactively(self-insert-command 1)
  call-interactively(self-insert-command nil nil)
  command-execute(self-insert-command)
```

The issue here is that location 1069 is the *end of buffer*. The `put-text-property(1069 1070 syntax-table (12))` tries to put a property ending on location 1070, which does not exist.. and thus this *args out of range error*.

So `nim-syntax-commentify` needs to be fixed.

I can give a stab at this next week.

**Comment by yuutayamada** [comment]
Thanks @kaushalmodi
the (1+ (point-at-eol))  was cause of this error.
As far as I remember, I implemented this line to use C-M-j, but now I
realized that it works without it...

Please update nim-mode and feel free to re-open, if the problem is still remaining.

(but I don't know why I can't reproduce issue myself...)

**Comment by kaushalmodi** [comment]
Thanks! I confirm the fix.

> (but I don't know why I can't reproduce issue myself...)

Let me find some time tomorrow to create an emacs -Q recipe for this.
