### ISSUE TITLE
Nim-mode breaks cider

### ISSUE THREAD

**Issue by joswik** [nim-lang/nim-mode#115]
I have the following problem when updating nim-mode and cider packages at the same time-
Cider package doesn't work and is premanently broken - i.e. restarting Emacs doesn't help (otherwise it wouldn't be a big problem).

I reported the issue to the cider side (github.com/clojure-emacs/cider/issues/1712) but they suggested to report it here too.

Note that I only tested this in Emacs 24.5 on Windows 7 (32-bit), and don't know if the same thing happens in Linux or Mac OS.

It would be too much trouble for you to install everything cider needs to work because there are many components, and it's not even necessary-
and the only thing you could see is this error: cider-jack-in: Invalid function: (repl-buff (cider-find-reusable-repl-buffer nil project-dir)).

Problems begin during installation of packages, and only in certain order i.e. when nim-mode is installed before cider in the SAME Emacs session. In all other cases everything works OK.

So, this is the quickest way to see what is going on:
 Empty .emacs.d directory with minimal init.el inside, pointing to melpa repository is enough.
 
Now, first install nim-mode from list-packages, then without restarting Emacs install cider from list-packages.
In `*Compile-Log*` buffer you can see more than 150 Warnings.

Next, wipe .emacs.d leaving only init.el. Now we are at default postion without packages.
Again, install nim-mode first, then restart Emacs, and then install cider. Now there are no warnings (or just a few) in `*Compile-Log*`.

Wipe .emacs.d again, but this time install cider first, don't restart Emacs, and then install nim-mode.
Again, no warnings in `*Compile-Log*.`

So, my problem is when there are updates for both packages at the same time like this a few days ago:
 `Install these 3 packages (nim-mode-20160418.18, magit-20160418.1513, cider-20160418.1513)? (y or n)` 

It seems that packages are installed in Z-to-A order, so nim-mode is always installed before cider,
and workaround is to unselect nim-mode, install everything else and only then can nim-mode be updated.

Can you analyze what is causing this?

I even tried to install nim-mode and then uninstall all its packages (from the list below), and then install cider, but no success.

Below you can see all packages when they are installed separately, and these 3 are used in both: epl, pkg-info, seq. Maybe one of them is the culprit?

nim-mode:
  commenter  -  20160219.827  installed             multiline-comment support package 
  company        -    20160424.1521 installed             Modular text completion framework
  concurrent     -    20160109.2046 installed             Concurrent utility functions for emacs lisp
  ctable         -    20140304.1659 installed             Table component for Emacs Lisp
  dash           -    20160306.1222 installed             A modern list library for Emacs
  deferred       -    20160109.2046 installed             Simple asynchronous functions for emacs lisp
  epc            -    20140609.2234 installed             A RPC stack for the Emacs Lisp
  epl            -    20150517.433  installed             Emacs Package Library
  flycheck       -    20160420.1312 installed             On-the-fly syntax checking
  let-alist      -    1.0.4         installed             Easily let-bind values of an assoc-list by their names
  nim-mode       -    20160418.18   installed             A major mode for the Nim programming language
  pkg-info       -    20150517.443  installed             Information about packages
  seq            -    2.15          installed             Sequence manipulation functions

cider:
  cider          -    20160425.2228 installed             Clojure Interactive Development Environment that Rocks
  clojure-mode   -    20160414.545  installed             Major mode for Clojure code
  epl            -    20150517.433  installed             Emacs Package Library
  pkg-info       -    20150517.443  installed             Information about packages
  queue          -    0.1.1         installed             Queue data structure
  seq            -    2.15          installed             Sequence manipulation functions
  spinner        -    1.7.1         installed             Add spinners and progress-bars to the mode-line for ongoing operations

Thanks!

**Comment by reactormonk** [comment]
You think you could bisect nim-mode to find out which commit introduces the problem?

**Comment by yuutayamada** [comment]
@joswik hi I don't check cider's source code yet, but
I think [this](https://github.com/nim-lang/nim-mode/blob/master/nim-helper.el#L941)
code is related package because I mimicked the way to use `if-let` from [here](https://github.com/clojure-emacs/cider/issues/1348), though this is just my assumption...

Once I wanted to use `if-let` in emacs 24.4 or 24.5, but if it's 
problem for other packages, I'm convincing to not to use them...

**Comment by yuutayamada** [comment]
I might lack of explanation. What I meant is if you install
nim-mode in emacs24.5, in the session the `if-let` or related functions are defined, so I thought it might break cider package if cider package is using same functions.

(the `if-let` will be provide from Emacs 25.1, so nim-mode is using it by defining in nim-helper.el.)

**Comment by joswik** [comment]
The issue is resolved and closed on the cider side.
I confirm that everything works OK now, so this can be closed too.
Thanks all.
