### ISSUE TITLE
Invalid temporary file name on Windows

### ISSUE THREAD

**Issue by SteamPoweredAnimal** [nim-lang/nim-mode#119]
I was setting up nim-mode on my Windows 10 PC when I happened upon an error related to temp file/directory creation: 
`eldoc error: (file-error Creating directory invalid argument e:/Temp/emacs-nim-modee:/Workspace).`
I've made some reserch and found problematic function in file **nim-suggest.el** in function _nim-suggest-get-temp-file-name_. For now I'm using temporary solution that should work for me fine (I explicitly name temporary file), but wanted to report that so it can be fixed in future.
On my linux machine I found no error.

**Comment by yuutayamada** [comment]
Thank you for letting me know the bug.
unfortunately I don't have windows environment, so could you check
following code? (just copy and past at scratch buffer and evaluate it)

```lisp
(progn
  (require 'nim-mode)
  (defun nim-suggest--file-name ()
  "Return buffer file name."
  (cl-case system-type
    ((ms-dos windows-nt cygwin)
     (concat "/"
             (replace-regexp-in-string
              ;; convert ":" to "꞉" (U+A789)
              ":" (char-to-string #xA789)
              buffer-file-name)))
    (t ; for *nix system
     buffer-file-name)))
  
  ;; Redefine this function
  (defun nim-suggest-get-temp-file-name ()
    (mapconcat 'directory-file-name
               `(,nim-dirty-directory ,(nim-suggest--file-name))
               ""))

  ) ; <- please type C-x C-e after the close parenthesis. it evaluate
    ; code inside progn
```

and then please check the bug if it's solved or not.

**Comment by SteamPoweredAnimal** [comment]
it worked like a charm.
