### ISSUE TITLE
ob-nim's test is failing

### ISSUE THREAD

**Issue by yuutayamada** [nim-lang/nim-mode#132]
I just fixed undefined variables for emacs24.5 to avoid waring and then I pushed, but the tests was failed: https://travis-ci.org/yuutayamada/nim-mode/jobs/147634004

@reactormonk Can I avoid an ob-nim's test? I suspect the undefined variables as I mentioned above may related to highlight problem at #100 because after I defined global-eldoc-mode variable I could see highlight in emacs24.5.

@Lompik Sorry, I didn't expect this kind of case. I don't like org-mode's source code and maintain nim-mode, org-mode and potentially nimsuggest (to add extra features) cause to much cost for me. Could you take care ob-nim.el in your repo? I'll help as much as I can if you have trouble with nim-mode or to port to MELPA.

**Comment by yuutayamada** [comment]
@Lompik I made sure manually that failed test. just I registered a keybind what's the test doing and I tried it on an empty org-mode buffer. The result was it seems working correctly. But somehow the test is failed.

inserted result:
```org
#+header: :var x = 3
#+begin_src nim :import sequtils strutils :define release ssl
when defined(release):
  when defined(ssl):
    var temp = @[1, 2].map (proc(i:int ) : string= $(i*x) )
    echo temp.join("/")
#+end_src

#+RESULTS:
: 3/6
```

I used this code to manually make sure:
```lisp
(defun my-obnim-test ()
  (interactive)
  (setq org-confirm-babel-evaluate nil)
  (org-babel-do-load-languages 'org-babel-load-languages
                               '((emacs-lisp . t) (nim . t) (org . t)))
  (insert "
#+header: :var x = 3
#+begin_src nim :import sequtils strutils :define release ssl
when defined(release):
  when defined(ssl):
    var temp = @[1, 2].map (proc(i:int ) : string= $(i*x) )
    echo temp.join(\"/\")
#+end_src")

  (goto-char 0)
  (org-babel-next-src-block)
  (org-babel-execute-src-block))
```

**Comment by Lompik** [comment]
I believe this was caused by nim's ssl module that failed to load on that particular VM. 

All tests are now passing: https://travis-ci.org/Lompik/nim-mode with this little change: https://github.com/Lompik/nim-mode/commit/0347e598da898267df20ce2bd25177ad2b692b4a .

I'm fine taking this it out although like I said before I am commited to maintain my contribution to `nim-mode` so that you don't have this burden on you and delegate it to me. 

Let me know if I should go ahead and create new package for it.

**Comment by yuutayamada** [comment]
> I'm fine taking this it out although like I said before I am commited to maintain my contribution to nim-mode so that you don't have this burden on you and delegate it to me.

In this issue, the real problem was that I needed to suspect my own code because the ob-nim's output was seemed ok and I was afraid if I were wrong because only cause of the change was me. I'm really appreciate your contribution of ob-nim, but I think managing it on separate repository is better way.

**Comment by yuutayamada** [comment]
@reactormonk what do you think about this? (Sorry, I asked this later)

**Comment by reactormonk** [comment]
@yuutayamada We could add @Lompik as contributor to nim-mode - this way we could avoid breaking his code, if we have a common test base.

**Comment by Lompik** [comment]
I stil think the test did not pass because of VM error. It wan't related to nim-mode at all. Possibly, nim failed to load the ssl libs for some reason. I have seen this happened

In fact , I took your exact same commit and all tests actually passed : [link to Travis](https://travis-ci.org/Lompik/nim-mode/builds/147828685).

**Comment by yuutayamada** [comment]
@reactormonk Does that mean I'll just mention him if I have trouble with ob-nim.el? and use `xit` to avoid test fail like this time? (I reconsidered and I don't have any objection to @Lompik to join nim-mode's contributor, but I would ask what kind of process I should take)

**Comment by reactormonk** [comment]
@yuutayamada Sounds like we need some kind of messaging platform. Gitter or IRC? Pick one and add it to the README.

**Comment by yuutayamada** [comment]
@Lompik Sorry for late reply, I saw your PR that remove ob-nim. I changed mind
as I wrote above, so if you still want to stay your ob-nim in
nim-mode, just change removing of ob-nim part of the PR.

**Comment by Lompik** [comment]
well, I'm now convinced otherwise. I realized there is no mutual dependancy between the two. Should such a dependancy come up in the future it will time to merge the projects again. How about we just it in `Other convenience packages` in the readme ?

**Comment by yuutayamada** [comment]
> How about we just it in Other convenience packages in the readme ?

Okay. I'll add your package in the readme. Let me know if nim-mode doesn't work with org-mode. I only use basic functions of org-mode (mainly outline), and I seem you are using org-mode pretty advanced ways.
