### ISSUE TITLE
nim-mode is spawning hundreads of nimsuggest processes without exiting them until the system crashes.

### ISSUE THREAD

**Issue by krux02** [nim-lang/nim-mode#134]
![screenshot](http://i.imgur.com/uDxgjTN.png)

**Comment by krux02** [comment]
you can simply verify this with this command in the shell:

    pgrep nimsuggest | wc -l

`pgrep` searches for processes by name, and prints all process numbers, one by line. `wc` is the word count program where `-l` specifies to only print the amount of lines. You can easily see that the number goes up, when you edit in emacs, but it never goes down.

**Comment by yuutayamada** [comment]
what is the nimsuggest's branch? I also failed to use master branch's nimsuggest, but major-restructure branch was ok.

**Comment by yuutayamada** [comment]
are those process numbers matched to your opened files?

**Comment by krux02** [comment]
I use the version that I get with `nimble install nimsuggest`.

**Comment by krux02** [comment]
I tried to install nimsuggest on the branch you suggested, but currently nimsuggest does not compile, neither via `nimble install nimsuggest` nor by manually checking it out on any branch. There is a compile problem in the compiler dependency.

**Comment by yuutayamada** [comment]
until few hours ago I could use nimsuggest (major-restructure branch's) with emacs's master branch, but now I fail to use. When I did ./test_main in nimsuggest's tests directory EPC (Emacs RPC)'s tests are passed. So, I re-built emacs with emacs-25 branch and nimsuggest works again.

Note that I'm also an end user of nimsuggest like you, so my way might be wrong. I'm using `nim e compile_without_nimble.nims` command to compile nimsuggest (not nimble install).

```sh
$ nim --version
Nim Compiler Version 0.14.3 (2016-07-27) [Linux: amd64]
Copyright (c) 2006-2016 by Andreas Rumpf

git hash: 27a40cd5a43175d273bf15af0ce0c269ea76a49b
active boot switches: -d:release
```
emacs version is "25.1.1" at 0f0b191

**Comment by yuutayamada** [comment]
I'm closing this issue because major-restructure branch was obsoleted and
now you can use nimsuggest's master branch (https://github.com/nim-lang/nimsuggest/pull/39).
