### ISSUE TITLE
nim-mode freezes in bigger files because of syntax-highlighting

### ISSUE THREAD

**Issue by yuutayamada** [nim-lang/nim-mode#139]
This issue was ported from #108 because some issues in there were
solved. (mainly nimsuggest related issues)
### The problem:

Nim-mode freezes when you move around in big files
(example https://github.com/nim-lang/opengl/blob/master/src/opengl.nim)
### Work around:

You can turn off syntax highlights by changing
`nim-syntax-disable-limit` and you can also specify the highlight
keyword group by `nim-syntax-disable-keywords-list`

**Comment by timmyjose** [comment]
I'll try these suggestions and revert with the specified data (as mentioned in #108) in case I still see the lag issue. Thanks!

**Comment by yuutayamada** [comment]
closing this because of #201
