### ISSUE TITLE
Indentation on space behaves hard to predict

### ISSUE THREAD

**Issue by krux02** [nim-lang/nim-mode#145]
Hell. When I hit the `space`-bar in nim-mode, some logic decides weather it should do an indentation level, or just insert a space. I really think this is very confusing, not only, because I do not see myself being able to predict weather a hit on space inserts one ore two spaces, but also I wouldn't hit space to insert indentation, I rather hit the tab key for that. Also a `backspace` hit is not guaranteed to revert the changes from a `space` key anymore.

All I would like to say is, that since I do not like this behavior and I think that it might also confuse other users, that it might be a good idea to turn this behavior off by default.

**Comment by yuutayamada** [comment]
AFAIK there is no binding for space key in nim-mode.

In my environment, all nim-mode's space key bindings return `nil`:

```lisp
;; tried at *scratch* buffer after opened a nim-mode buffer.
;; (C-x C-e at end of close paren outputs result of `lookup-key`)
(lookup-key nim-mode-map (kbd "SPC"))
(lookup-key nimsuggest-mode-map (kbd "SPC"))
(lookup-key nim-compile-mode-map (kbd "SPC"))
```

**Comment by krux02** [comment]
When I first posted this, I was still struggling a bit with emacs. I just looked up what actually happens when I press space (`<f1> k <SPC>`) and it inserts the char and then runs `auto-fill-function`, because ` ` is in the `auto-fill-chars`. I think I just have to take it out.
