### ISSUE TITLE
too many errors -> flycheck stops working

### ISSUE THREAD

**Issue by krux02** [nim-lang/nim-mode#146]
Sometimes, when the code has too many errors, I get an error reported that there are too many errors. Then flycheck just stops updating the errors in the buffer. Meaning the when I correct things and the errors should disapper that doesn't happen anymore. I do not know how to get flycheck working again from there unless I reopen that file.

I understand, that flycheck can only handle a certain degree of errors, but I do not like that I get a popup that tells me that there are too many errors, it should rather be somewhere in a log file that does not open up on screen. I think the best default behavior for the user would be to truncate the errors to an amount that flycheck can handle before they are sent for visualization.

**Comment by yuutayamada** [comment]
> I think the best default behavior for the user would be to truncate the errors to an amount that flycheck can handle before they are sent for visualization.

agreed, but this needs to be fixed both emacs side and nimsuggest side, which EPC protocol was used emacs and vscode...

BTW do you know that nimsuggest handle config.nims? hope it reduce your nim's code errors. (I was away to check nim's development, so my point might be wrong though)
