### ISSUE TITLE
symbol of own file/module is not found

### ISSUE THREAD

**Issue by krux02** [nim-lang/nim-mode#147]
referencing to the current module shows as an error from emacs:

test.nim
```Nim
proc foo(i: int): void =
  if i > 0:
    echo i
    test.foo(i - 1) #undeclared identifier test
```
but when I compile it, there is no error at all.

Probably that is because flycheck does for some reason not know the file name from the file it currently processes, or it has a wrong name.

**Comment by yuutayamada** [comment]
I couldn't reproduce your issue on nim 0.16.0 with included nimsuggest.

Are you sure that you are using flycheck-nimsuggest? (not flycheck-nim)

![screenshot from 2017-02-26 15-52-13](https://cloud.githubusercontent.com/assets/1082473/23345020/c8b9c060-fc3b-11e6-9321-e3f3cbbd6f80.png)

**Comment by krux02** [comment]
I just tried it today again, and it seems to work now. So maybe over time it got fixed in _nimsuggest_ without me taking notice of it.

**Comment by krux02** [comment]
Aparently it was the flycheck-nimsuggest/flycheck-nim difference. It would be nice though, if the readme would cover that difference a bit cleaner, because until now I was not aware of that difference.

**Comment by krux02** [comment]
yea nim-nimsuggest is even another package. I installed it when I have no idea what I was doing.
