### ISSUE TITLE
compile error regexp

### ISSUE THREAD

**Issue by krux02** [nim-lang/nim-mode#148]
I just wanted to mention, that I implemented a regular expression, so that emacs can parse the error messages from Nim in the compilation buffer. This is all I needed:

```elisp

;; saves all buffers and compiles current file (why would you ever not want to save before compilation?)
;; still allows to customize the compilation command from 'compile

(global-set-key (kbd "<S-f9>") (lambda () (interactive)
  (save-some-buffers t)
	(call-interactively 'compile)))

;; Just does the last compilation again. So you don't need to go back to your main file to compile, you can just compile

(global-set-key (kbd "<f9>")
	(lambda () (interactive)
	  (save-some-buffers t)
  	(save-window-excursion
  		(switch-to-buffer-other-window "*compilation*")
			(recompile)
		)))

;; disable colors, because it introduces problems with parsing of locations and sometimes they are visualized wrongly, and it is recolored anyway
;; excessiveStackTrace prints full path stack traces, that is important otherwise the regular expression can't parse, where it comes from
;; also makes imenu (S-tab) contain some useful information.

(add-hook 'nim-mode-hook (lambda ()
 (setq-local compile-command (concat "nim compile --colors:off --excessiveStackTrace:on --debugger:native --verbosity:0 -r --hint\\[Processing\\]:off " (shell-quote-argument buffer-file-name)))
 (setq-local imenu-generic-expression '(("proc"  "^proc\\W*\\(\\w*\\)" 1)
        ("type"     "^type\\W*\\(\\w*\\)" 1)
        ("template"     "^template\\W*\\(\\w*\\)" 1)
        ("macro"     "^macro\\W*\\(\\w*\\)" 1)
				("block"     "^block\\W*\\(\\w*\\)" 1)
				("section" "^ *###+ *\\([^#\n]+?\\) *###+ *$" 1)))))

(add-to-list 'compilation-error-regexp-alist 'nim)
```

Personally I don't use nim-compile, just normal compile. All it needs, is to change the default for compile command for nim buffers.

```elisp
(add-hook 'nim-mode-hook (lambda ()
 (setq-local compile-command (concat "nim c --colors:off -r  "
  (file-name-sans-extension buffer-file-name)))))
```

I disabled colors because of #149 

I just wanted to mention, this blog post helped me doing this:
http://praveen.kumar.in/2011/03/09/making-gnu-emacs-detect-custom-error-messages-a-maven-example/

I would do a pull request, but I don't know where to put it, and in general what it needs to test plugins.

**Comment by yuutayamada** [comment]
Sorry, I'm not sure what you are trying to do, but I think it may worth mentioning about https://github.com/syohex/emacs-quickrun if you want *just* a simple compile method. (though I'm open to discuss ideal compile method, but please make another separate issue)

**Comment by krux02** [comment]
the first section makes links to files in the compilation output clickable. So the compilation buffer knows about the file and line of the error. This did not work before. The second part is not so important, it just sets a buffer local variable in nim-mode, so that the default compile built into emacs does not start with "make -k ". That is not necessary when you build with nim-compile. My approach here was to customize the default built of emacs, instead of using a command that only works in emacs. But I guess that part is just preference. You can just ignore that part, because it's not really that important.

**Comment by krux02** [comment]
<a href="http://i.imgur.com/sthpK8X.png">
  <img src="http://imgur.com/sthpK8Xl.png" />
</a>

**Comment by yuutayamada** [comment]
looks nice. You can put it into nim-compile.el

**Comment by krux02** [comment]
Well I have no idea how to develop a plugin in emacs, or how to even test my changes. I have put the changes in the folding of the plugin. But the plugin folder is not a git repository, so changes there are not affecting my fork of this repository. So, how do I test and develop that changes so that they work in this plugin?

**Comment by krux02** [comment]
In case you want to adopt the changes, I added some stuff.

**Comment by yuutayamada** [comment]
Closing this issue because of  #163
