### ISSUE TITLE
nimscript-mode comment highlighting doesn't stop at newline

### ISSUE THREAD

**Issue by nigredo-tori** [nim-lang/nim-mode#166]
OS: Ubuntu 16.04
Emacs: 26.0.50
nim-mode: 20170716.948
nim, nimsuggest: 0.17.0 (d3f0f87e81e262ee25fd528aae5b6db0bdf78d5e)

No relevant messages in `*Messages*` buffer. Found nothing similar in README.md

The problem is like follows: with `nimscript-mode` all lines after a single-line comment (started by `#` symbol) are also highlighted as comments:
![screenshot from 2017-07-26 16-46-42](https://user-images.githubusercontent.com/5962285/28615556-b2df5620-7223-11e7-8286-afa3c1007cab.png)
The same file opened in `nim-mode` is displayed properly.
The issue is present with and without my init file.

**Comment by yuutayamada** [comment]
Can you give me the link of config.nims?

**Comment by yuutayamada** [comment]
Never mind I could reproduce

**Comment by yuutayamada** [comment]
I think I fixed the issue, but feel free to re-open if you still have same issue

**Comment by nigredo-tori** [comment]
@yuutayamada, it is fixed for my scripts, too. Thank you.
