### ISSUE TITLE
compilation error regexp broken for stacktrace

### ISSUE THREAD

**Issue by krux02** [nim-lang/nim-mode#171]
In the past, entries from the stack trace were clickable, now this does not work anymore since this commit: https://github.com/nim-lang/nim-mode/commit/474d4c716fcc6cf058b1aa582d0cf9dfc236fdbf. Entries in the stack trace do not have a column. That part needs to stay optional. 

My current compilation error regexp is this:

```elisp
(add-to-list
 'compilation-error-regexp-alist-alist
 '(nim "^\\([[:alnum:]\\/_.-]*\\.nims?\\)(\\([[:digit:]]*\\)\\(?:, ?\\([[:digit:]]*\\)\\)?) \\(Warning:\\)?\\(\\(?:template/generic instantiation from here\\)\\|\\(?:Hint:\\)\\)?\\(?:Error\\)?" 1 2 3 (4 . 5)))
```
This also changes that a hint is not seen as a warning, but just a compiler message.

**Comment by yuutayamada** [comment]
Sorry about that. I don't like to having emacs' regex and wanted to use rx.el

>  Entries in the stack trace do not have a column. That part needs to stay optional.

Which part are you referring? or can you show me test code for that?

> This also changes that a hint is not seen as a warning, but just a compiler message.

Should the "Hint" be treated as INFO? I'm not sure the difference though

**Comment by krux02** [comment]
and normally I use ``re-builder`` within emacs. Very helpful.
