### ISSUE TITLE
Melpa nim-mode <> flycheck-nimsuggest dependency issue

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/nim-mode#187]
Conforming Bugs
===============

Please tell us below:

- [x] basic information
   - OS name -- RHEL 6.6
   - Versions: Emacs 25.3, Nim compiler 0.17.3 (devel d47fec5bccde33f84a8c5e31d70dcaae184191a5), and nimsuggest (gives same version info as that of nim)
- [x] Are you using latest version of nim-mode?
- [x] Are there message related to nim-mode in `*Messages*` buffer?
   Yes, emacs errors at `package-initialize` itself: See below.
- [x] Did you read README.md?
- [x] Is your problem related to nimsuggest-mode? (company-mode, flycheck, or el-doc)
  Most likely due to the recent inter-dependency between `nim-mode` and `flycheck-nimsuggest`.
   - [x] Did you try nim-mode without nimsugggest-mode? What happened?
         That does not help as the issue happens during package initialization. My nim config isn't even getting loaded yet.

And describe your problem:

- At emacs startup, I get this error at the time of `package-initialize`:

```
Debugger entered--Lisp error: (error "Unable to activate package ‘flycheck-nimsuggest’.
Required package ‘nim-mode-0.4.1’ is unavailable")
  signal(error ("Unable to activate package ‘flycheck-nimsuggest’.\nRequired package ‘nim-mode-0.4.1’ is unavailable"))
  error("Unable to activate package `%s'.\nRequired package `%s-%s' is unavailable" flycheck-nimsuggest nim-mode "0.4.1")
  package-activate-1([cl-struct-package-desc flycheck-nimsuggest (20171025 135) "flycheck backend for Nim using nimsuggest" ((flycheck (0 23)) (nim-mode (0 4 1)) (emacs (24 3))) nil nil "/home/kmodi/.emacs.d/elpa_25/flycheck-nimsuggest-20171025.135" ((:url . "https://github.com/yuutayamada/flycheck-nimsuggest") (:commit . "b0b094874d4759224174eaacee1d210a181f6f55")) nil] nil deps)
  package-activate(flycheck-nimsuggest)
  package-initialize()
  eval-buffer(#<buffer  *load*-851140> nil "/home/kmodi/.emacs.d/setup-packages.el" nil t)  ; Reading at buffer position 4044
  load-with-code-conversion("/home/kmodi/.emacs.d/setup-packages.el" "/home/kmodi/.emacs.d/setup-packages.el" nil t)
  load("~/.emacs.d/setup-packages.el" nil :nomessage)
  eval-buffer(#<buffer  *load*> nil "/home/kmodi/.emacs.d/init.el" nil t)  ; Reading at buffer position 6862
```

**Comment by kaushalmodi** [comment]
Workaround was to remove `nim-mode` dependency from `flycheck-nimsuggest`:

Editted `flycheck-nimsuggest-pkg.el` to be this (removed the `(nim-mode "0.4.1")` form):

```el
;;; -*- no-byte-compile: t -*-
(define-package "flycheck-nimsuggest" "20171025.135" "flycheck backend for Nim using nimsuggest" '((flycheck "0.23")  (emacs "24.3")) :commit "b0b094874d4759224174eaacee1d210a181f6f55" :url "https://github.com/yuutayamada/flycheck-nimsuggest")
```

I believe you've got a circular dependency issue here.. just make `nim-mode` depend on `flycheck-nimsuggest` (not the other way around too).

**Comment by yuutayamada** [comment]
thanks @kaushalmodi I've updated flycheck-nimsuggest (might take awhile MELPA is updated though)

**Comment by kaushalmodi** [comment]
Thanks. I confirm the fix.
