### ISSUE TITLE
Don't make indentation default

### ISSUE THREAD

**Issue by reactormonk** [nim-lang/nim-mode#19]
> Also in my emacs the indentation is indenting the previous row when I press enter which is really irritating when you want to leave a block, backspace to dedent, start a new expression and it all jumps back out when I press enter. Is that intentional, not happening in your solution (perhaps a collision with my .emacs) or something you also wish you didnt have?

**Comment by reactormonk** [comment]
If you want to disable indentation, customize `nim-indent-trigger-commands`.

**Comment by lisptime** [comment]
I also have this problem, is this the default behavior?

**Comment by reactormonk** [comment]
@lisptime What's a good default behavior? Should I bind enter-and-indent to `C-j` instead?

**Comment by necrodome** [comment]
Isn't this a bug with indent level calculation?

**Comment by reactormonk** [comment]
Might be, but I don't see how you could leave empty lines in code otherwise.

**Comment by necrodome** [comment]
My elisp-fu is not strong, so I can't help much but python mode is handling that correctly so coud it be helpful checking that?

**Comment by filcuc** [comment]
I'm having the same issue. Clean install of emacs and installed current version on nim-mode from git.
In my opinion the enter key should act as following:
- when the current line open a new block, as C-J
- else, as enter-and-indent

**Comment by yuutayamada** [comment]
I think this is because of `electric-indent-mode`.
https://www.gnu.org/software/emacs/manual/html_node/emacs/Indent-Convenience.html

> Electric Indent mode is a global minor mode that automatically indents the line after every RET you type. This mode is enabled by default. To toggle this minor mode, type M-x electric-indent-mode. To toggle the mode in a single buffer, use M-x electric-indent-local-mode. 

Does your indentation change if you turn off `electric-indent-mode`?

**Comment by reactormonk** [comment]
Should be fixed with the new python based setup - reopen if it's still an issue.
