### ISSUE TITLE
font-lock-mode too slow

### ISSUE THREAD

**Issue by krux02** [nim-lang/nim-mode#198]
When editing big files, such as [gl.nim](https://github.com/krux02/opengl-sandbox/blob/master/glad/gl.nim) scrolling blocks for several seconds until syntax highlighting has been resolved for the file. After syntax highlighting for that file has been resolved scrolling works, but editing in that file remains a bad experience so that I need to disable it in that file.

Arch Linux
emacs 26.1
no messages in `*Messages*` buffer.
not related to ``nimsuggest``, ``company``, ``flycheck`` or ``el-doc``. It is all disabled.

**Comment by krux02** [comment]
At this current point, I don't know how emacs does syntax highlighting, but I could profile the matchers, and it seems that most time is wasted in `nim-pragma-matcher` and `nim-type-matcher`.

**Comment by krux02** [comment]
As a workaround disable `font-lock-mode` and then call `M-x` `font-lock-fontify-buffer`. 
This doesn't fix anything, but at least it makes editing a bigger nim file possible without missing out in Nim syntax highlighting entirely.

**Comment by yuutayamada** [comment]
@krux02 is this issue fixed by your PR?

**Comment by krux02** [comment]
yes it is. Sorry I forgot to close this.
