### ISSUE TITLE
What is nim-fill-docstring-style for?

### ISSUE THREAD

**Issue by krux02** [nim-lang/nim-mode#206]
Nim doesn't have _docstrings_, so what is the point of having nim-fill-docstring-style if there are no docstrings in Nim?

The point is I want to remove it, because it is unnecessary. The question is, what should be the fixed behavior for Nim?

**Comment by yuutayamada** [comment]
There are some burden that I and original author inherited from python-mode.el or python.el. I agree removing it. I'm not sure original behavior of python, so I'm happy if someone can clarify if the function is really need it.

**Comment by krux02** [comment]
well fill on a multiline string isn't wrong but treating it as a docstring is certainly wrong. I didn't use auto-fill-mode a lot yet, but I think for that mode I think there should be a setting to enable/disable filling for multiline string literals. Those literals could have semantic newlines that should better not be "filled".

I wonder where the term "fill" comes from, it is not really filling anything. I had struggle to understand what it means in the beginning, but it is nothing more than arranging line endings.
