### ISSUE TITLE
Nimsuggest epc error "Nim compiler not in PATH"

### ISSUE THREAD

**Issue by greenfork** [nim-lang/nim-mode#225]
Conforming Bugs
===============

Please tell us below:

- [x] basic information
   - OS name: VoidLinux
   - Versions: Emacs 26.2, Nim compiler 0.19.9, and nimsuggest 0.19.9
- [x] Are you using latest version of nim-mode?
- [x] Are there message related to nim-mode in `*Messages*` buffer?
- [x] Did you read README.md?
- [x] Is your problem related to nimsuggest-mode? (company-mode, flycheck, or el-doc)
   - [x] Did you try nim-mode without nimsugggest-mode? What happened?
         (Comment out nimsuggest-mode's config please)
         all good

And describe your problem:

Whenever I open an Emacs with nim file, I see this error:

```
deferred error : (error "Server may raise an error Use \"M-x epc:pop-to-last-server-process-buffer RET\" to see full traceback:
nimsuggest.nim(627)      handleCmdLine
Error: unhandled exception: Cannot find Nim standard library: Nim compiler not in PATH [IOError]

Process epc:server:2 exited abnormally with code 1
```

which is this line https://github.com/nim-lang/Nim/blob/devel/nimsuggest/nimsuggest.nim#L627

Executing `nimsuggest filename.nim` works fine, continuously outputs messages like

```
usage: sug|con|def|use|dus|chk|mod|highlight|outline|known file.nim[;dirtyfile.nim]:line:col
type 'quit' to quit
type 'debug' to toggle debug mode on/off
type 'terse' to toggle terse mode on/off
```

and executing

```nim
import os
findExe("nim")
```

correctly outputs my binary location.

The gist is that nimsuggest doesn't work for my Emacs buffers.

**Comment by zestyr** [comment]
Emacs uses it's own internal PATH variable, which may differ from your normal one. I had to fix a similar issue by doing this in my init file:
```elisp
(setenv "PATH" (concat (getenv "PATH") ":/home/zed/.nimble/bin"))
(setq exec-path (append exec-path '("/home/zed/.nimble/bin")))
(setq nimsuggest-path "/home/zed/.nimble/bin/nimsuggest")
```

**Comment by greenfork** [comment]
@zestyr thank you so much, that solved the issue!
