### ISSUE TITLE
Font-locking fails when `font-lock-maximum-decoration` is an alist

### ISSUE THREAD

**Issue by zk-phi** [nim-lang/nim-mode#228]
Conforming Bugs
===============

Please tell us below:

- [x] basic information
   - OS name: [Mac OS]
   - Versions: Emacs [26.1], Nim compiler [1.0.4]
- [x] Are you using latest version of nim-mode? [YES]
- [x] Are there message related to nim-mode in `*Messages*` buffer? [YES]
- [x] Did you read README.md? [YES]
- [x] Is your problem related to nimsuggest-mode? (company-mode, flycheck, or el-doc) [NO]
   - [x] Did you try nim-mode without nimsugggest-mode? What happened?
         (Comment out nimsuggest-mode's config please)
   - [nimsuggest-mode is not installed but the error occurs]

And describe your problem:

When `font-lock-maximum-decoration` is an alist (`((cperl-mode . 1) (t . t))` in my environment), `nim-mode` fails to font-lock the buffer with `invalid-function` error (seen in the `*Messages*` buffer).

I also tried to call `font-lock-fontify-region` manually and got following backtrace:

```
Debugger entered--Lisp error: (invalid-function ("\\(?:^\\|;\\) *\\_<\\(?:\\(?:converter\\|func\\|iterator\\|m\\(?:acro\\|ethod\\)\\|proc\\|template\\)\\)\\_> +\\(\\(?:[[:alpha:]]\\(?:_\\|[[:alnum:]]\\)*\\|`[]-_!$-&*-/<-@[|~[:alnum:]]+?`\\) *\\(\\*\\)?\\)" (1 (if (match-string 2) 'nim-font-lock-export-face font-lock-function-name-face) keep t)))
("\\(?:^\\|;\\) *\\_<\\(?:\\(?:converter\\|func\\|iterator\\|m\\(?:acro\\|ethod\\)\\|proc\\|template\\)\\)\\_> +\\(\\(?:[[:alpha:]]\\(?:_\\|[[:alnum:]]\\)*\\|`[]-_!$-&*-/<-@[|~[:alnum:]]+?`\\) *\\(\\*\\)?\\)" (1 (if (match-string 2) 'nim-font-lock-export-face font-lock-function-name-face) keep t))(184)
font-lock-fontify-keywords-region(1 184 nil)
font-lock-default-fontify-region(1 184 nil)
font-lock-fontify-region(1 184)
eval((font-lock-fontify-region (point-min) (point-max)) nil)
```

This does not occur when `font-lock-maximum-decoration` is `t`, which is the default value.

**Comment by krux02** [comment]
Thanks a lot for the feedback. I think this should be easy to fix.
