### ISSUE TITLE
deferred error : (void-function incf)

### ISSUE THREAD

**Issue by dankeyy** [nim-lang/nim-mode#239]
Conforming Bugs
===============

Please tell us below:

- basic information
   - OS name endeavourOS
   - Versions: Emacs 27.2, Nim compiler 1.6.0 (installed via choosenim), and nimsuggest i think 1.6 too
- [Y] Are you using latest version of nim-mode?
- [ deferred error : (void-function incf)] Are there message related to nim-mode in `*Messages*` buffer?
- [ Y] Did you read README.md?
- [ DK] Is your problem related to nimsuggest-mode? (company-mode, flycheck, or el-doc)
   - [ Y] Did you try nim-mode without nimsugggest-mode? What happened?
         (Comment out nimsuggest-mode's config please)
not sure where that config is or if i have one
And describe your problem:
M-x nim-mode gives `deferred error : (void-function incf)`. there is no completion or anything. nothing works.

thanks ahead

**Comment by egregius313** [comment]
This should be fixed by #237.
