### ISSUE TITLE
 Package-install ends with: error: scan-error: (Unbalanced parentheses 3514 17751)

### ISSUE THREAD

**Issue by arjenduinhouwer** [nim-lang/nim-mode#249]
Conforming Bugs
===============

Please tell us below:

- [ ] basic information
   - Linux, Ubuntu 22.04 LTS
   - Versions: Emacs 27.1, nim 2.0, 
- [x] Are you using latest version of nim-mode? YES
- [ ] Are there message related to nim-mode in `*Messages*` buffer? No, just the message mentioned in the title directly after install. 
- [ ] Did you read README.md? yes
- [ ] Is your problem related to nimsuggest-mode? (company-mode, flycheck, or el-doc) no

And describe your problem:

I've been using nim-mode before, but on another machine. Today was the first time installing it on this machine. The error message comes directly in the mini buffer after it got downloaded from Melpa. 

`autoload-generate-file-autoloads: nim-mode.el:0:0: error: scan-error: (Unbalanced parentheses 3514 17751)`

Nim-mode will not work after this, I cannot manually invoke it either. No further messages are produced.

Please let me know if you'd like me to deliver more information.

**Comment by Vindaar** [comment]
Hmm, I worry this is a regression due to the changes from #245. Maybe Emacs 27 struggles with 
```elisp
    (modify-syntax-entry ?# ". 124b" nim-mode-syntax-table)
    (modify-syntax-entry ?[ ". 23" nim-mode-syntax-table))
```
somehow (at least it confuses `rainbow-delimiters-mode` as well). But Emacs 29 is perfectly happy with it.

Can you verify if it works fine if you change these lines back to 

```elisp
    (modify-syntax-entry ?# "<" nim-mode-syntax-table))
```

?
