### ISSUE TITLE
dependency on epc

### ISSUE THREAD

**Issue by lyro** [nim-lang/nim-mode#29]
The dependency on the epc elpa package is missing.

**Comment by reactormonk** [comment]
How do you do that? I can't find it anywhere in the melpa readme. @purcell some help?

**Comment by lyro** [comment]
You have to put the dependency in the comment header at the beginning of the file, e.g. the following should work
```
;; Package-Requires: ((emacs "24") (epc "0.1"))
```

**Comment by reactormonk** [comment]
Try this one.
