### ISSUE TITLE
Display "thing-at-point"

### ISSUE THREAD

**Issue by reactormonk** [nim-lang/nim-mode#3]
Similar to elisp, display the signature (and types) in the minibuffer.

**Comment by pigmej** [comment]
On `epc` branch this would be possible with nimsuggest `con`.

**Comment by pigmej** [comment]
In my branch (which is created from my epc branch) in https://github.com/pigmej/nim-mode/commit/6641902b2517688a5ae756b1ae76002ed135a816 I created some very very basic call-signatures.

I checked eldoc, but it doesn't support async. So I made it "by hand" (very very basic), but emacs-jedi also uses their own version.

To make it fully working we would need:
* use correct function face,
* detect cursor position, and highlight correct argument,
* solve multiple signatures.
* add some idle timer, to display signature when one really want it.

**Comment by reactormonk** [comment]
Just make it sync. Create a `nim-epc-call-sync` which calls epc sync. On the other hand, how do modes like ensime and cedet do it?

**Comment by pigmej** [comment]
well, `eldoc` itself gives us not a lot "nice" things, we will still need to parse everything, and prepare data for eldoc itself. Having/using eldoc itself would probably mean a lot of hacks.

emacs-jedi: https://github.com/tkf/emacs-jedi/blob/master/jedi-core.el#L667

semantic (cedet) uses also hand-coded echo area by default.

I will check what we can do there in next days.

**Comment by pigmej** [comment]
It will work, I have some "concept" but it needs improvement/rewrite.

What's also cool. We will have more than call signatures.

**Comment by reactormonk** [comment]
Fixed by https://github.com/nim-lang/nim-mode/pull/36
