### ISSUE TITLE
Test line-checking fails

### ISSUE THREAD

**Issue by reactormonk** [nim-lang/nim-mode#39]
Should it be

    let
      a = 1
      # comment
    let
      b = 3

or

    let
      a = 1
    # comment
    let
      b = 3

?

**Comment by yuutayamada** [comment]
Sorry, I was misunderstanding about the test code. #40 should be fixed.
I added a checking code whether "previous line" is empty or comment. So I should have 
added a empty line.

**Comment by reactormonk** [comment]
If you also add "fixes #40" to the PR or commit, it automatically closes this issue.
