### ISSUE TITLE
Indentation for if expression

### ISSUE THREAD

**Issue by vegansk** [nim-lang/nim-mode#76]
This is how ``nim-mode`` indents multiltine ``if`` expression

```nimrod
let x = if true:
  "a"
else:
  "b"
```

It must be:
```nimrod
let x = if true:
    "a"
  else:
    "b"
```

**Comment by yuutayamada** [comment]
I think your example's `else` must be same indent level as `if`.
(I guess it's typo, but for clarification)

hmm it's strange.
I manually made sure your examples in emacs' master branch and 
it indented as I expected. Also I added indentation tests from your examples
and the tests were passed both emacs 24.4 and 24.5.
Which emacs version are you using? Did you clean install nim-mode already?

**Comment by vegansk** [comment]
@yuutayamada, it's from  Ubuntu 14.04 repos:
```
GNU Emacs 24.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.10.7) 
of 2014-03-08 on lamiak, modified by Debian
```

Will try to upgrade it and recheck the issue

**Comment by vegansk** [comment]
So, latest nim-mode on emacs 24.5 works well.
