### ISSUE TITLE
Change case to pcase, ' to ` and what is first?

### ISSUE THREAD

**Issue by AllNamesRTaken** [nim-lang/nim-mode#8]
I am using emacs in windows and the cases dont work, but if I change them to pcase they do.
Also in the branches from the pcase the first ' needs to be a ` to work.
Now all work except that it doesnt seem to understand first. I looks like a function that does something with a string but I dont have it.

**Comment by reactormonk** [comment]
I can't find a pcase anywhere in the code, what are you referring to?

**Comment by AllNamesRTaken** [comment]
What i meant was that thr cases didnt work for me and locally i had to use
pcase instead.

**Comment by reactormonk** [comment]
Which instance of case?

**Comment by AllNamesRTaken** [comment]
(let ((ppss (or syntax-ppss (syntax-ppss))))
    (pcase type
      (comment (and (nth 4 ppss) (nth 8 ppss)))
      (string (and (not (nth 4 ppss)) (nth 8 ppss)))
      (paren (nth 1 ppss))
      (t nil))))

and

      (save-excursion
        (pcase context-status
          (`no-indent 0)

and the latter is also where I had to change ' vs `
Note: I am not a lisp guy and really no idea of what Im doing, Im just debugging and making it run.

But changing those makes it run on Windows  8 emacs 24.3.1

What is up with the "first" command. What is it, where is it defined and what should I do?

**Comment by reactormonk** [comment]
Try `C-h f first` for describing functions. If that makes it run with windows, please make a pull request.

**Comment by AllNamesRTaken** [comment]
Sorry for not responding, but my time has been elsewhere occupied.
The thing is that first does not exist in my windows version of emacs. in
other words, Ctrl+h f first, doesnt give anythine. I would assume that it
maybe takes the first of a list?

Maybe you can copy the code for first and pass it to me?

2015-01-05 4:03 GMT+01:00 reactormonk <notifications@github.com>:

**Comment by AllNamesRTaken** [comment]
I send you my nim-mode.el and you can just ctrl-s "pcase" and see what I
did and if it makes sense.

2015-01-04 19:47 GMT+01:00 reactormonk <notifications@github.com>:

**Comment by reactormonk** [comment]
Could you send an ordinary pull request? https://help.github.com/articles/using-pull-requests/

**Comment by reactormonk** [comment]
Try again with emacs > 24.3

**Comment by yuutayamada** [comment]
Hi @AllNamesRTaken, I think your problem was missing `(require 'cl-lib)`
because both `case` and `first` are included in the cl-lib (as cl-case and cl-first).
But currently latest nim-mode needs emacs 24.4 or later and necessary the `cl-lib`s are 
fixed (I think), so please update both nim-mode and emacs.

**Comment by yuutayamada** [comment]
I'm closing this issue because of long term no reaction. Please re-open or make new issue if you have the problem.
